//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACI_WEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModel : DbContext
    {
        public DBModel()
            : base("name=DBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Aplicativo> Aplicativo { get; set; }
        public DbSet<Equipo> Equipo { get; set; }
        public DbSet<Perfil> Perfil { get; set; }
        public DbSet<SubTipo> SubTipo { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Ticket> Ticket { get; set; }
        public DbSet<Tipo> Tipo { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Derivaciones> Derivaciones { get; set; }
        public DbSet<Responsable> Responsable { get; set; }
    }
}
