//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACI_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        public Equipo()
        {
            this.Aplicativo = new HashSet<Aplicativo>();
            this.Ticket = new HashSet<Ticket>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int codequipo { get; set; }
        public string equipo1 { get; set; }
        public string gerencia { get; set; }
        public string area { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual ICollection<Aplicativo> Aplicativo { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
