//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACI_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Responsable
    {
        public int codresponsable { get; set; }
        public string responsable1 { get; set; }
    }
}
