//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACI_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubTipo
    {
        public SubTipo()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int codsubtipo { get; set; }
        public string subtipo1 { get; set; }
        public Nullable<int> codtipo { get; set; }
    
        public virtual Tipo Tipo { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
