//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACI_WEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Ticket
    {
        [DisplayName("Ticket")]
        public string idticket { get; set; }
        public string matricula { get; set; }
        public Nullable<int> codequipo { get; set; }
        public Nullable<int> codaplicativo { get; set; }
        public Nullable<int> codtipo { get; set; }
        public Nullable<int> codsubtipo { get; set; }
        [DisplayName("Asunto")]
        public string asunto { get; set; }
        [DisplayName("Detalle")]
        public string descripcion { get; set; }
        [DisplayName("Fecha")]
        public Nullable<System.DateTime> fechaingreso { get; set; }
        public Nullable<System.DateTime> fechaatencion { get; set; }
        [DisplayName("Estado")]
        public string estado { get; set; }
        [DisplayName("Respuesta")]
        public string comentariofinal { get; set; }
        public Nullable<int> feedback { get; set; }
        public string comentariofeedback { get; set; }
        [DisplayName("Matricula")]
        public string matricula_responsable { get; set; }
        public string causa { get; set; }
        public string accion_inmediata { get; set; }
        public Nullable<int> codresponsable { get; set; }
        public string matricula_modelo { get; set; }
        public Nullable<int> cantidad_clientes { get; set; }
        public Nullable<int> cantidad_cuentas { get; set; }
        public Nullable<decimal> deuda_vencida { get; set; }
        public Nullable<decimal> deuda_total { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual SubTipo SubTipo { get; set; }
        public virtual Tipo Tipo { get; set; }
        public virtual Usuario Usuario { get; set; }

        public string matricula_origen { get; set; }
        public string matricula_nueva { get; set; }
        public string motivo { get; set; }

        public int tipoderivacion { get; set; }
    }
}
