//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACI_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo
    {
        public Tipo()
        {
            this.SubTipo = new HashSet<SubTipo>();
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int codtipo { get; set; }
        public string tipo1 { get; set; }
        public Nullable<int> codequipo { get; set; }
    
        public virtual ICollection<SubTipo> SubTipo { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
