//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACI_WEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        public Usuario()
        {
            this.Aplicativo = new HashSet<Aplicativo>();
            this.Ticket = new HashSet<Ticket>();
        }

        [DisplayName("Matricula")]
        [Required(ErrorMessage = "Debe ingresar su matricula")]
        public string matricula { get; set; }
        public string nombres { get; set; }
        public string ap_paterno { get; set; }
        public string ap_materno { get; set; }
        public string puesto { get; set; }
        [DisplayName("Clave de Red")]
        [Required(ErrorMessage = "Debe ingresar su clave de red")]
        [DataType(DataType.Password)]
        public string pass { get; set; }
        public string imgpath { get; set; }
        public Nullable<int> codequipo { get; set; }
        public Nullable<int> codperfil { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual ICollection<Aplicativo> Aplicativo { get; set; }
        public virtual Equipo Equipo { get; set; }
        public virtual Perfil Perfil { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }

        public string LoginErrorMessage;
    }
}
